# Generated by Django 5.1.15 on 2026-02-13

import netfields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="supernet",
            field=netfields.fields.CidrAddressField(
                blank=True,
                help_text="Override. Null = inherit from project.",
                null=True,
            ),
        ),
    ]
