# Generated by Django 5.1.15 on 2026-02-13 21:36

import django.db.models.deletion
import netfields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_site_supernet'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteWanAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', netfields.fields.InetAddressField(help_text='WAN IP address', max_length=39)),
                ('label', models.CharField(help_text='e.g. ISP1, Fiber, LTE backup', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wan_addresses', to='projects.site')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
    ]
