# Generated by Django 5.1.15 on 2026-02-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_sitewanaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitewanaddress',
            name='ip_address',
            field=models.CharField(help_text='WAN IP or DNS hostname (e.g. 203.0.113.1, office.dyndns.org)', max_length=255),
        ),
    ]
