# Generated by Django 5.1.15 on 2026-02-15 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_wan_address_charfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
    ]
