# Generated by Django 5.1.15 on 2026-02-11 20:13

import django.core.validators
import django.db.models.deletion
import netfields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', netfields.fields.CidrAddressField(help_text='Network in CIDR notation, e.g. 10.0.1.0/24', max_length=43)),
                ('gateway', netfields.fields.InetAddressField(blank=True, help_text='Gateway IP address', max_length=39, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ipam_subnet',
                'ordering': ['network'],
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', netfields.fields.InetAddressField(help_text='Host IP address', max_length=39)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('mac_address', models.CharField(blank=True, help_text='MAC address (XX:XX:XX:XX:XX:XX)', max_length=17)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('reserved', 'Reserved'), ('dhcp', 'DHCP'), ('decommissioned', 'Decommissioned')], default='planned', max_length=20)),
                ('device_type', models.CharField(choices=[('server', 'Server'), ('router', 'Router'), ('switch', 'Switch'), ('firewall', 'Firewall'), ('ap', 'Access Point'), ('camera', 'Camera'), ('printer', 'Printer'), ('phone', 'Phone'), ('workstation', 'Workstation'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='ipam.subnet')),
            ],
            options={
                'db_table': 'ipam_host',
                'ordering': ['ip_address'],
            },
        ),
        migrations.CreateModel(
            name='Tunnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tunnel_type', models.CharField(choices=[('gre', 'GRE'), ('ipsec', 'IPsec'), ('vxlan', 'VXLAN'), ('wireguard', 'WireGuard')], max_length=20)),
                ('tunnel_subnet', netfields.fields.CidrAddressField(help_text='Tunnel subnet (/30 or /31)', max_length=43)),
                ('ip_a', netfields.fields.InetAddressField(help_text='Tunnel IP for site A', max_length=39)),
                ('ip_b', netfields.fields.InetAddressField(help_text='Tunnel IP for site B', max_length=39)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('down', 'Down')], default='planned', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tunnels', to='projects.project')),
                ('site_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tunnels_as_a', to='projects.site')),
                ('site_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tunnels_as_b', to='projects.site')),
            ],
            options={
                'db_table': 'ipam_tunnel',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VLAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan_id', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4094)])),
                ('name', models.CharField(max_length=100)),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlans', to='projects.site')),
            ],
            options={
                'verbose_name': 'VLAN',
                'verbose_name_plural': 'VLANs',
                'db_table': 'ipam_vlan',
                'ordering': ['vlan_id'],
                'unique_together': {('site', 'vlan_id')},
            },
        ),
        migrations.AddField(
            model_name='subnet',
            name='vlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subnets', to='ipam.vlan'),
        ),
    ]
