# Generated by Django 5.1.15 on 2026-02-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='status',
        ),
        migrations.AlterField(
            model_name='host',
            name='device_type',
            field=models.CharField(choices=[('server', 'Server'), ('router', 'Router'), ('switch', 'Switch'), ('firewall', 'Firewall'), ('ap', 'Access Point'), ('nas', 'NAS'), ('camera', 'Camera'), ('printer', 'Printer'), ('phone', 'Phone'), ('workstation', 'Workstation'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
