# Generated by Django 5.1.15 on 2026-02-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0004_subnet_site_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tunnel',
            name='status',
        ),
        migrations.AddField(
            model_name='tunnel',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
