# Generated by Django 5.1.15 on 2026-02-16 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0005_tunnel_status_to_enabled'),
        ('projects', '0005_remove_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tunnel',
            name='external_endpoint',
            field=models.CharField(blank=True, default='', help_text='External endpoint name/IP (when site_b is null)', max_length=300),
        ),
        migrations.AlterField(
            model_name='tunnel',
            name='site_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tunnels_as_b', to='projects.site'),
        ),
    ]
