# Generated by Django 5.1.15 on 2026-02-17 08:26

import django.db.models.deletion
import netfields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0006_cross_project_tunnels'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='ip_type',
            field=models.CharField(choices=[('static', 'Static IP'), ('dhcp_lease', 'DHCP Static Lease')], default='static', max_length=20),
        ),
        migrations.CreateModel(
            name='DHCPPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_ip', netfields.fields.InetAddressField(help_text='Start of DHCP range', max_length=39)),
                ('end_ip', netfields.fields.InetAddressField(help_text='End of DHCP range', max_length=39)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dhcp_pools', to='ipam.subnet')),
            ],
            options={
                'db_table': 'ipam_dhcp_pool',
                'ordering': ['start_ip'],
            },
        ),
        migrations.AddField(
            model_name='host',
            name='dhcp_pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='ipam.dhcppool'),
        ),
    ]
