# Generated by Django 5.1.15 on 2026-02-28 10:06

from django.db import migrations, models

DEFAULT_DEVICE_TYPES = [
    ("server", "Server", 0),
    ("router", "Router", 1),
    ("switch", "Switch", 2),
    ("firewall", "Firewall", 3),
    ("ap", "Access Point", 4),
    ("nas", "NAS", 5),
    ("camera", "Camera", 6),
    ("printer", "Printer", 7),
    ("phone", "Phone", 8),
    ("workstation", "Workstation", 9),
    ("other", "Other", 10),
]


def seed_device_types(apps, schema_editor):
    DeviceType = apps.get_model("ipam", "DeviceType")
    for value, label, position in DEFAULT_DEVICE_TYPES:
        DeviceType.objects.get_or_create(
            value=value,
            defaults={"label": label, "position": position},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0007_host_ip_type_dhcppool_host_dhcp_pool'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'ipam_device_type',
                'ordering': ['position', 'label'],
            },
        ),
        migrations.AlterField(
            model_name='host',
            name='device_type',
            field=models.CharField(default='other', max_length=50),
        ),
        migrations.RunPython(seed_device_types, migrations.RunPython.noop),
    ]
