# Generated by Django 5.1.15 on 2026-02-28 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0008_device_type_configurable'),
        ('projects', '0005_remove_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevicePort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('port_type', models.CharField(default='rj45', max_length=30)),
                ('position', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='ipam.host')),
            ],
            options={
                'db_table': 'ipam_device_port',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Cable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cable_type', models.CharField(default='cat6', max_length=30)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('port_a', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cable_as_a', to='ipam.deviceport')),
                ('port_b', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cable_as_b', to='ipam.deviceport')),
            ],
            options={
                'db_table': 'ipam_cable',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='PatchPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('port_count', models.PositiveIntegerField(default=24)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patch_panels', to='projects.site')),
            ],
            options={
                'db_table': 'ipam_patch_panel',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='deviceport',
            name='patch_panel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='ipam.patchpanel'),
        ),
        migrations.CreateModel(
            name='PortTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('port_type', models.CharField(default='rj45', max_length=30)),
                ('position', models.PositiveIntegerField(default=0)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_templates', to='ipam.devicetype')),
            ],
            options={
                'db_table': 'ipam_port_template',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='deviceport',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('host__isnull', False), ('patch_panel__isnull', True)), models.Q(('host__isnull', True), ('patch_panel__isnull', False)), _connector='OR'), name='port_belongs_to_one_device'),
        ),
        migrations.AlterUniqueTogether(
            name='porttemplate',
            unique_together={('device_type', 'name')},
        ),
    ]
