# Generated by Django 5.1.15 on 2026-02-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0009_physical_topology'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetype',
            name='color',
            field=models.CharField(default='#3b82f6', max_length=7),
        ),
    ]
