# Generated by Django 5.1.15 on 2026-02-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0013_port_profile_step3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
