# Generated by Django 5.1.15 on 2026-03-01 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0014_alter_portprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cable',
            name='port_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cable_as_a', to='ipam.deviceport'),
        ),
        migrations.AlterField(
            model_name='cable',
            name='port_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cable_as_b', to='ipam.deviceport'),
        ),
    ]
